### ISSUE TITLE
Some general doubts

### ISSUE THREAD

**Issue by gijo-varghese** [kartsims/vue-customelement-bundler#5]
Hi, Thanks for such an amazing library! Works really cool. I've been searching for a long time. Loved it!!

I'm planning to build a full-featured chat widget for websites. It will give users a widget to put in the website and a dashboard where they can chat with users. 

For the chat widget, I'm planning to use this library. But here some of my doubts before finalizing. Can someone pls help me with these

1) What if I want to add external libraries like Socket IO or Axios or anything like that. If I install these using NPM, will it be embedded inside the js file after build? Or I've to add it manually via <script> tag in the HTML file?

2) Similar as above, what about CSS files like Bootstrap?

3) How's is the browser compatibility?

4) Roolup.js isn't working for me. Any tips to reduce the file size further?

4) Any other tips/suggestions for chat widget if I use this?

**Comment by kartsims** [comment]
Sorry for not answering all these sooner.

This issue is getting old and not directly related to the library. I wish someone would have answered your concerns and hope you have been able to accomplish this chat widget.

If you are now able to answer them yourself, I'd love to hear your thoughts.
