### ISSUE TITLE
Web component polyfill

### ISSUE THREAD

**Issue by visualjerk** [kartsims/vue-customelement-bundler#7]
It would be nice, if you added the web component polyfill for usage in older browsers.

In main.js:

```javascript
import 'document-register-element/build/document-register-element'
```

**Comment by kartsims** [comment]
Sure, please send in a PR I'll by happy to merge !

**Comment by kartsims** [comment]
Added a line in the README as everyone may not wish to support these browsers.

Thanks for opening the issue !
